name: "CI/CD"
on:
  - push
  - pull_request

jobs:

  lint:
    name: lint
    uses: wolcomm/.github/.github/workflows/rust-lint.yml@rm-actions-rs

  test:
    name: test
    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable, nightly]
        args:
          - --lib
          - --test versions
          # TODO: exclude until crate has stabilised
          # - --test prefix-sets
          - --test prefix-set-proptests
        include:
          - toolchain: nightly
            args: --doc
    uses: wolcomm/.github/.github/workflows/rust-test.yml@rm-actions-rs
    with:
      toolchain: ${{ matrix.toolchain }}
      args: ${{ matrix.args }}
    secrets: inherit

  publish:
    name: publish
    if: ${{ github.event_name == 'push' &&
            startsWith(github.ref, 'refs/tag') }}
    needs:
      - lint
      - test
    uses: wolcomm/.github/.github/workflows/rust-publish.yml@rm-actions-rs
    secrets: inherit
